// Dweve HEDL - Hierarchical Entity Data Language
//
// Copyright (c) 2025 Dweve IP B.V. and individual contributors.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License in the LICENSE file at the
// root of this repository or at: http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Async Neo4j client for executing HEDL operations.
//!
//! This module provides async APIs for executing Cypher statements
//! generated by the `to_cypher` functions with connection pooling
//! and concurrent execution support.
//!
//! # Features
//!
//! - **Connection Pooling**: Automatic connection pool management
//! - **Concurrent Execution**: Execute multiple statements in parallel
//! - **Retry Logic**: Automatic retry with exponential backoff
//! - **Transaction Support**: ACID guarantees for operations
//! - **Smart Batching**: Group independent operations for parallel execution
//!
//! # Example
//!
//! ```no_run
//! use hedl_neo4j::{AsyncNeo4jClient, ToCypherConfig};
//! use hedl_core::Document;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! // Connect to Neo4j
//! let client = AsyncNeo4jClient::connect(
//!     "bolt://localhost:7687",
//!     "neo4j",
//!     "password",
//! ).await?;
//!
//! // Import HEDL document
//! let doc: Document = todo!();
//! client.import_document(&doc).await?;
//! # Ok(())
//! # }
//! ```

#[cfg(feature = "async")]
use neo4rs::{ConfigBuilder, Graph, Query};
use std::sync::Arc;
use std::time::Duration;

use crate::config::ToCypherConfig;
use crate::cypher::{CypherStatement, StatementType};
use crate::error::{Neo4jError, Result};
use hedl_core::Document;

/// Default maximum number of retry attempts for transient errors.
const DEFAULT_MAX_RETRIES: u32 = 3;

/// Default initial retry delay in milliseconds.
const DEFAULT_INITIAL_RETRY_DELAY_MS: u64 = 100;

/// Maximum retry delay in milliseconds (10 seconds).
const MAX_RETRY_DELAY_MS: u64 = 10_000;

/// Async Neo4j client with connection pooling.
///
/// This client provides async methods for executing Cypher statements
/// with automatic connection pooling, retries, and concurrent execution.
#[cfg(feature = "async")]
#[derive(Clone)]
pub struct AsyncNeo4jClient {
    graph: Arc<Graph>,
    config: ToCypherConfig,
    max_retries: u32,
    initial_retry_delay: Duration,
}

#[cfg(feature = "async")]
impl AsyncNeo4jClient {
    /// Create a new async client with default configuration.
    ///
    /// # Arguments
    ///
    /// * `uri` - Neo4j connection URI (e.g., "<bolt://localhost:7687>")
    /// * `user` - Database username
    /// * `password` - Database password
    ///
    /// # Errors
    ///
    /// Returns an error if connection to Neo4j fails.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::AsyncNeo4jClient;
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?;
    /// # Ok(())
    /// # }
    /// ```
    pub async fn connect(uri: &str, user: &str, password: &str) -> Result<Self> {
        let config = ConfigBuilder::default()
            .uri(uri)
            .user(user)
            .password(password)
            .build()
            .map_err(|e| Neo4jError::HedlError(format!("Failed to build Neo4j config: {e}")))?;

        let graph = Arc::new(
            Graph::connect(config)
                .map_err(|e| Neo4jError::HedlError(format!("Failed to connect to Neo4j: {e}")))?,
        );

        Ok(Self {
            graph,
            config: ToCypherConfig::default(),
            max_retries: DEFAULT_MAX_RETRIES,
            initial_retry_delay: Duration::from_millis(DEFAULT_INITIAL_RETRY_DELAY_MS),
        })
    }

    /// Set Cypher generation config.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::{AsyncNeo4jClient, ToCypherConfig};
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?
    /// .with_config(ToCypherConfig::new().with_create());
    /// # Ok(())
    /// # }
    /// ```
    #[must_use]
    pub fn with_config(mut self, config: ToCypherConfig) -> Self {
        self.config = config;
        self
    }

    /// Set maximum retry attempts for transient errors.
    ///
    /// Default is 3 retries.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::AsyncNeo4jClient;
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?
    /// .with_max_retries(5);
    /// # Ok(())
    /// # }
    /// ```
    #[must_use]
    pub fn with_max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = max_retries;
        self
    }

    /// Set initial retry delay for exponential backoff.
    ///
    /// Default is 100ms.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::AsyncNeo4jClient;
    /// # use std::time::Duration;
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?
    /// .with_initial_retry_delay(Duration::from_millis(200));
    /// # Ok(())
    /// # }
    /// ```
    #[must_use]
    pub fn with_initial_retry_delay(mut self, delay: Duration) -> Self {
        self.initial_retry_delay = delay;
        self
    }

    /// Execute a single statement without retry.
    ///
    /// # Arguments
    ///
    /// * `stmt` - The Cypher statement to execute
    ///
    /// # Errors
    ///
    /// Returns an error if query execution fails.
    pub async fn execute_statement(&self, stmt: &CypherStatement) -> Result<()> {
        let query = stmt.render_inline();
        self.graph
            .run(Query::new(query))
            .await
            .map_err(|e| Neo4jError::HedlError(format!("Failed to execute statement: {e}")))?;
        Ok(())
    }

    /// Execute a single statement with retry logic.
    ///
    /// Automatically retries on transient errors with exponential backoff.
    ///
    /// # Arguments
    ///
    /// * `stmt` - The Cypher statement to execute
    ///
    /// # Errors
    ///
    /// Returns an error if all retry attempts fail.
    pub async fn execute_statement_with_retry(&self, stmt: &CypherStatement) -> Result<()> {
        let mut retries = 0;
        let mut delay = self.initial_retry_delay;

        loop {
            match self.execute_statement(stmt).await {
                Ok(()) => return Ok(()),
                Err(e) if retries < self.max_retries && is_retryable(&e) => {
                    retries += 1;
                    tokio::time::sleep(delay).await;
                    delay = std::cmp::min(delay * 2, Duration::from_millis(MAX_RETRY_DELAY_MS));
                }
                Err(e) => return Err(e),
            }
        }
    }

    /// Execute statements sequentially.
    ///
    /// Each statement is executed one after another, with retry logic.
    ///
    /// # Arguments
    ///
    /// * `stmts` - The Cypher statements to execute
    ///
    /// # Errors
    ///
    /// Returns an error if any statement execution fails.
    pub async fn execute_statements(&self, stmts: &[CypherStatement]) -> Result<()> {
        for stmt in stmts {
            self.execute_statement_with_retry(stmt).await?;
        }
        Ok(())
    }

    /// Execute statements concurrently.
    ///
    /// All statements are executed in parallel up to the connection pool size.
    /// This provides significant performance improvements for independent operations.
    ///
    /// # Arguments
    ///
    /// * `stmts` - The Cypher statements to execute concurrently
    ///
    /// # Errors
    ///
    /// Returns an error if any statement execution fails.
    ///
    /// # Performance
    ///
    /// For N statements with pool size P, execution time is approximately:
    /// `(N / P) * avg_statement_time` instead of `N * avg_statement_time`
    pub async fn execute_statements_concurrent(&self, stmts: &[CypherStatement]) -> Result<()> {
        if stmts.is_empty() {
            return Ok(());
        }

        let tasks: Vec<_> = stmts
            .iter()
            .map(|stmt| {
                let graph = self.graph.clone();
                let query = stmt.render_inline();
                let max_retries = self.max_retries;
                let initial_delay = self.initial_retry_delay;

                tokio::spawn(async move {
                    execute_query_with_retry(&graph, query, max_retries, initial_delay).await
                })
            })
            .collect();

        // Wait for all tasks and collect errors
        for (idx, task) in tasks.into_iter().enumerate() {
            task.await
                .map_err(|e| Neo4jError::HedlError(format!("Task {idx} panicked: {e}")))??;
        }

        Ok(())
    }

    /// Import a HEDL document to Neo4j with optimized execution.
    ///
    /// This method:
    /// 1. Generates Cypher statements from the document
    /// 2. Executes constraints sequentially (required)
    /// 3. Executes node and relationship creation concurrently
    ///
    /// # Arguments
    ///
    /// * `doc` - The HEDL document to import
    ///
    /// # Errors
    ///
    /// Returns an error if document conversion or execution fails.
    ///
    /// # Performance
    ///
    /// This method provides 3-5× speedup over sequential execution for
    /// documents with multiple batches.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::AsyncNeo4jClient;
    /// # use hedl_core::Document;
    /// # async fn example(doc: Document) -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?;
    ///
    /// client.import_document(&doc).await?;
    /// # Ok(())
    /// # }
    /// ```
    pub async fn import_document(&self, doc: &Document) -> Result<()> {
        let stmts = crate::to_cypher_statements(doc, &self.config)?;
        self.import_document_from_statements(&stmts).await
    }

    /// Import a HEDL document from pre-generated statements.
    ///
    /// This is useful when you want to generate statements once and
    /// reuse them or modify them before execution.
    ///
    /// # Arguments
    ///
    /// * `stmts` - Pre-generated Cypher statements
    ///
    /// # Errors
    ///
    /// Returns an error if execution fails.
    pub async fn import_document_from_statements(&self, stmts: &[CypherStatement]) -> Result<()> {
        let groups = group_statements_by_dependency(stmts);

        // Execute each group (groups must be sequential, but within each group can be parallel)
        for group in groups {
            if !group.is_empty() {
                self.execute_statements_concurrent(&group).await?;
            }
        }

        Ok(())
    }

    /// Import a HEDL document within a transaction.
    ///
    /// All statements are executed within a single transaction,
    /// providing ACID guarantees. If any statement fails, the
    /// entire transaction is rolled back.
    ///
    /// # Arguments
    ///
    /// * `doc` - The HEDL document to import
    ///
    /// # Errors
    ///
    /// Returns an error if document conversion or execution fails.
    ///
    /// # Performance
    ///
    /// Transactions add ~10% overhead but provide stronger consistency
    /// guarantees. Use this when data integrity is critical.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::AsyncNeo4jClient;
    /// # use hedl_core::Document;
    /// # async fn example(doc: Document) -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?;
    ///
    /// // All-or-nothing import
    /// client.import_document_transactional(&doc).await?;
    /// # Ok(())
    /// # }
    /// ```
    pub async fn import_document_transactional(&self, doc: &Document) -> Result<()> {
        let stmts = crate::to_cypher_statements(doc, &self.config)?;

        // Separate schema operations from data operations
        // Neo4j forbids mixing schema modifications with write operations in the same transaction
        let (schema_stmts, data_stmts): (Vec<_>, Vec<_>) = stmts.into_iter().partition(|s| {
            matches!(
                s.statement_type,
                StatementType::Constraint | StatementType::Index
            )
        });

        // Execute schema statements outside transaction (each in its own implicit transaction)
        // Schema operations in Neo4j are auto-committed and cannot be part of explicit transactions
        for stmt in &schema_stmts {
            let query = stmt.render_inline();
            self.graph
                .run(Query::new(query))
                .await
                .map_err(|e| Neo4jError::HedlError(format!("Schema operation failed: {e}")))?;
        }

        // Execute data statements in a transaction for ACID guarantees
        if !data_stmts.is_empty() {
            let mut txn =
                self.graph.start_txn().await.map_err(|e| {
                    Neo4jError::HedlError(format!("Failed to start transaction: {e}"))
                })?;

            for stmt in &data_stmts {
                let query = stmt.render_inline();
                txn.run(Query::new(query)).await.map_err(|e| {
                    Neo4jError::HedlError(format!("Transaction execution failed: {e}"))
                })?;
            }

            txn.commit()
                .await
                .map_err(|e| Neo4jError::HedlError(format!("Transaction commit failed: {e}")))?;
        }

        Ok(())
    }

    /// Execute a raw Cypher query.
    ///
    /// This is useful for custom queries not covered by the high-level API.
    ///
    /// # Arguments
    ///
    /// * `query` - The Cypher query string
    ///
    /// # Errors
    ///
    /// Returns an error if query execution fails.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use hedl_neo4j::AsyncNeo4jClient;
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// let client = AsyncNeo4jClient::connect(
    ///     "bolt://localhost:7687",
    ///     "neo4j",
    ///     "password",
    /// ).await?;
    ///
    /// client.execute_query("MATCH (n) RETURN count(n)").await?;
    /// # Ok(())
    /// # }
    /// ```
    pub async fn execute_query(&self, query: &str) -> Result<()> {
        self.graph
            .run(Query::new(query.to_string()))
            .await
            .map_err(|e| Neo4jError::HedlError(format!("Query execution failed: {e}")))?;
        Ok(())
    }
}

/// Group statements by dependency for optimal concurrent execution.
///
/// Returns groups where:
/// - Group 1: Constraints (must execute first, sequentially)
/// - Group 2: All node creation statements (can execute in parallel)
/// - Group 3: All relationship statements (can execute in parallel, but after nodes)
///
/// This grouping maximizes parallelism while respecting dependencies.
fn group_statements_by_dependency(stmts: &[CypherStatement]) -> Vec<Vec<CypherStatement>> {
    let mut groups = Vec::new();

    // Group 1: Constraints and indexes (must be first)
    let constraints: Vec<_> = stmts
        .iter()
        .filter(|s| {
            matches!(
                s.statement_type,
                StatementType::Constraint | StatementType::Index
            )
        })
        .cloned()
        .collect();
    if !constraints.is_empty() {
        groups.push(constraints);
    }

    // Group 2: Node creation (independent, can be parallel)
    let nodes: Vec<_> = stmts
        .iter()
        .filter(|s| matches!(s.statement_type, StatementType::CreateNode))
        .cloned()
        .collect();
    if !nodes.is_empty() {
        groups.push(nodes);
    }

    // Group 3: Relationships (depend on nodes)
    let rels: Vec<_> = stmts
        .iter()
        .filter(|s| matches!(s.statement_type, StatementType::CreateRelationship))
        .cloned()
        .collect();
    if !rels.is_empty() {
        groups.push(rels);
    }

    // Group 4: Everything else (property updates, etc.)
    let other: Vec<_> = stmts
        .iter()
        .filter(|s| {
            !matches!(
                s.statement_type,
                StatementType::Constraint
                    | StatementType::Index
                    | StatementType::CreateNode
                    | StatementType::CreateRelationship
            )
        })
        .cloned()
        .collect();
    if !other.is_empty() {
        groups.push(other);
    }

    groups
}

/// Check if an error is retryable.
///
/// Transient errors like connection issues and timeouts are retryable.
/// Data errors and constraint violations are not.
fn is_retryable(err: &Neo4jError) -> bool {
    match err {
        Neo4jError::HedlError(msg) => {
            let msg_lower = msg.to_lowercase();
            msg_lower.contains("connection")
                || msg_lower.contains("timeout")
                || msg_lower.contains("unavailable")
                || msg_lower.contains("network")
                || msg_lower.contains("io error")
        }
        _ => false,
    }
}

/// Execute a query with retry logic (helper function for concurrent execution).
#[cfg(feature = "async")]
async fn execute_query_with_retry(
    graph: &Arc<Graph>,
    query: String,
    max_retries: u32,
    initial_delay: Duration,
) -> Result<()> {
    let mut retries = 0;
    let mut delay = initial_delay;

    loop {
        match graph.run(Query::new(query.clone())).await {
            Ok(()) => return Ok(()),
            Err(e) => {
                let err = Neo4jError::HedlError(format!("Query execution failed: {e}"));
                if retries < max_retries && is_retryable(&err) {
                    retries += 1;
                    tokio::time::sleep(delay).await;
                    delay = std::cmp::min(delay * 2, Duration::from_millis(MAX_RETRY_DELAY_MS));
                } else {
                    return Err(err);
                }
            }
        }
    }
}

#[cfg(all(test, feature = "async"))]
mod tests {
    use super::*;

    #[test]
    fn test_group_statements_empty() {
        let stmts = vec![];
        let groups = group_statements_by_dependency(&stmts);
        assert_eq!(groups.len(), 0);
    }

    #[test]
    fn test_group_statements_constraints_only() {
        let stmts = vec![CypherStatement::new(
            "CREATE CONSTRAINT".to_string(),
            StatementType::Constraint,
        )];
        let groups = group_statements_by_dependency(&stmts);
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].len(), 1);
        assert!(matches!(
            groups[0][0].statement_type,
            StatementType::Constraint
        ));
    }

    #[test]
    fn test_group_statements_mixed() {
        let stmts = vec![
            CypherStatement::new("CREATE CONSTRAINT".to_string(), StatementType::Constraint),
            CypherStatement::new("CREATE NODE".to_string(), StatementType::CreateNode),
            CypherStatement::new("CREATE NODE 2".to_string(), StatementType::CreateNode),
            CypherStatement::new("CREATE REL".to_string(), StatementType::CreateRelationship),
        ];
        let groups = group_statements_by_dependency(&stmts);
        assert_eq!(groups.len(), 3);

        // Group 1: Constraints
        assert_eq!(groups[0].len(), 1);
        assert!(matches!(
            groups[0][0].statement_type,
            StatementType::Constraint
        ));

        // Group 2: Nodes
        assert_eq!(groups[1].len(), 2);
        assert!(matches!(
            groups[1][0].statement_type,
            StatementType::CreateNode
        ));

        // Group 3: Relationships
        assert_eq!(groups[2].len(), 1);
        assert!(matches!(
            groups[2][0].statement_type,
            StatementType::CreateRelationship
        ));
    }

    #[test]
    fn test_is_retryable() {
        // Retryable errors
        assert!(is_retryable(&Neo4jError::HedlError(
            "connection failed".to_string()
        )));
        assert!(is_retryable(&Neo4jError::HedlError(
            "timeout occurred".to_string()
        )));
        assert!(is_retryable(&Neo4jError::HedlError(
            "service unavailable".to_string()
        )));

        // Non-retryable errors
        assert!(!is_retryable(&Neo4jError::HedlError(
            "constraint violation".to_string()
        )));
        assert!(!is_retryable(&Neo4jError::InvalidReference(
            "bad ref".to_string()
        )));
    }

    #[test]
    fn test_is_retryable_case_insensitive() {
        assert!(is_retryable(&Neo4jError::HedlError(
            "CONNECTION FAILED".to_string()
        )));
        assert!(is_retryable(&Neo4jError::HedlError(
            "TIMEOUT OCCURRED".to_string()
        )));
    }
}
