[package]
name = "hedl-yaml-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.hedl-yaml]
path = ".."

[dependencies.hedl-core]
path = "../../hedl-core"

# Prevent this from interfering with workspace
[workspace]
members = ["."]

[[bin]]
name = "fuzz_yaml_to_hedl"
path = "fuzz_targets/fuzz_yaml_to_hedl.rs"
test = false
doc = false

[[bin]]
name = "fuzz_hedl_to_yaml"
path = "fuzz_targets/fuzz_hedl_to_yaml.rs"
test = false
doc = false
